sudo: required
services:
- docker
before_install:
- docker build -t dkawanam/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run dkawanam/react-test npm test -- --coverage
after_success:
- docker build -t dkawanam/multi-client ./client
- docker build -t dkawanam/multi-nginx ./nginx
- docker build -t dkawanam/multi-server ./server
- docker build -t dkawanam/multi-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push dkawanam/multi-client
- docker push dkawanam/multi-nginx
- docker push dkawanam/multi-server
- docker push dkawanam/multi-worker

notifications:
  slack:
    secure: IJMX14BF04kxN778zAC5DaHbzEsyvjA4VyXD1lbcr2Pec08EEe08C7eYBBOs3vv5b3ySzdw4kvQmBNOZ76BcckWEwN3ephPZiNs/j7BYiiNIvxkdtS4dyfqpIMtUhafDddF+3/hr0V/hd1hK6OAK5+aaLheBi+9rzqhH92Q20TY9Dayq96Syioekwh69UetotKfcF2rZucrzAi0ZEfJCqiABaJZ6jiFZVCVxhSqx4KzBnfWNjTq/OZELbOuL+HTpkXNp93YheDLNujVF73grRsddrjXKEadSDBVIhprn/FZTghKRXIBB7vFcL99kcdigJF8TvRFynYABEpbLou8lxKcEoW5LSMX2CxyFNA5EYGQAq3q7Zua94X/kduAolBxHfzoDj8QTha74Jni7m3wKGDrVHuMaMqs/Isk2JtEKoxKKW1DTCgAHJnhiEfyJvdZDpwqeyEQgYU7DAEcjDxLKlm2k7OjjHkLdGG4rLlgWeV/xRnY+2ZBeKc+BNG6eCwO3vQwFEqleuw1ZP+ZqLeQzhimH/lIR2CmnMq95P5GAtGifYJyM4rrxCgtcURhQHhHLmQavD/1FYKDbqz/uultTuciD0kDa7u4dJ66d9AmPV2ljEysQvA7V3dHkx3Lcih1tyx59zKaXtg9qDczM8NoN14gNzKyyjxkDg+lRTN5yMj4=

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-884871223445
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
